const Strings = {
  login: 'Login',
  accessTheApp: 'Acesse o aplicativo',
  email: 'Email',
  emailPlaceholder: 'examplo@email.com',
  password: 'Senha',
  passwordPlaceholder: 'sua senha',
  signin: 'ENTRAR',
  thisFieldIsRequired: 'Este campo é obrigatório',
  enterAValidEmailAddress: 'Digite um e-mail válido',
  titleScreenStopRecord: 'Registro de parada',
  titleScreenSynchronize: 'Sincronizar dados',
  titleScreenStoppingPlaces: 'Paradas',
  save: 'SALVAR',
  minutes: 'MIN',
  equipment: 'Equipamento',
  farm: 'Fazenda',
  field: 'Talhão',
  reason: 'Motivo da parada',
  note: 'Nota da parada',
  equipmentPlaceholder: 'TR 6170J',
  serialNumberPlaceholder: '1CQS690ACK0125217',
  farmPlaceholder: 'Fazenda Modelo',
  fieldPlaceholder: 'TH 01',
  selectFarm: 'Selecione uma fazenda',
  filterPlaceholder: 'Localizar registros',
  RegistersNotFound: 'Nenhum registro encontrado',
  sync: 'Sincronizar',
};

export default Strings;
